# voidrunner — generated by ~/dotfiles/theme/render.py; do not edit
# exec'd by ~/.ipython/profile_default/ipython_config.py with `c` in scope.
from pygments.token import Token

try:
    c  # noqa: B018  (defined by the config file that execs us)
except NameError:  # run standalone: nothing to do
    c = get_config()  # noqa: F821

c.TerminalInteractiveShell.true_color = True
c.TerminalInteractiveShell.highlighting_style_overrides = {
    Token.Comment: "italic #585858",
    Token.Comment.Single: "italic #585858",
    Token.Keyword: "#bdfe58",
    Token.Keyword.Constant: "#99ccff",
    Token.Keyword.Namespace: "#4b8902",
    Token.Keyword.Type: "#99ccff",
    Token.Name: "#f1f1f1",
    Token.Name.Builtin: "#5eeeaf",
    Token.Name.Builtin.Pseudo: "italic #99ccff",
    Token.Name.Class: "#99ccff",
    Token.Name.Decorator: "#bdfe58",
    Token.Name.Exception: "#99ccff",
    Token.Name.Function: "bold #5eeeaf",
    Token.Name.Namespace: "#9e9e9e",
    Token.Name.Variable: "#f1f1f1",
    Token.Literal.String: "#e5ccff",
    Token.Literal.String.Doc: "italic #585858",
    Token.Literal.String.Escape: "#5eeeaf",
    Token.Literal.Number: "#b2d8d8",
    Token.Operator: "#5eeeaf",
    Token.Operator.Word: "#bdfe58",
    Token.Punctuation: "#9e9e9e",
    Token.Error: "#dea6a0",
    Token.Prompt: "#5eeeaf",
    Token.PromptNum: "bold #5eeeaf",
    Token.OutPrompt: "#e5ccff",
    Token.OutPromptNum: "bold #e5ccff",
}
