-- nvim-dap signs and nvim-dap-view
return function(p, c)
  return {
    DapBreakpoint = { fg = p.red },
    DapBreakpointCondition = { fg = p.butter },
    DapBreakpointRejected = { fg = p.dim },
    DapLogPoint = { fg = p.sky },
    DapStopped = { fg = p.lime },
    DapStoppedLine = { bg = p.bg2 },
    NvimDapViewControlNext = { fg = p.mint },
    NvimDapViewControlStepInto = { fg = p.sky },
    NvimDapViewControlStepOut = { fg = p.sky },
    NvimDapViewControlStepBack = { fg = p.lav },
    NvimDapViewControlPause = { fg = p.butter },
    NvimDapViewControlPlay = { fg = p.lime },
    NvimDapViewControlRunLast = { fg = p.teal },
    NvimDapViewControlTerminate = { fg = p.rose },
    NvimDapViewControlDisconnect = { fg = p.peach },
    NvimDapViewControlNC = { fg = p.dim },
    NvimDapViewTab = { fg = p.dim, bg = p.bg1 },
    NvimDapViewTabSelected = { fg = p.bg1, bg = p.lime, bold = true },
    NvimDapViewWatchText = { fg = p.fg },
    NvimDapViewWatchError = { fg = p.rose },
    NvimDapViewWatchUpdated = { fg = p.butter },
    NvimDapViewExceptionFilterEnabled = { fg = p.mint },
    NvimDapViewExceptionFilterDisabled = { fg = p.dim },
    NvimDapViewFileName = { fg = p.sky },
    NvimDapViewLineNumber = { fg = p.lnr },
    NvimDapViewSeparator = { fg = p.border },
    NvimDapViewThreadStopped = { fg = p.rose },
    NvimDapViewFrameName = { fg = p.func },
    NvimDapViewValue = { fg = p.teal },
  }
end
