-- lazy.nvim UI
return function(p, c)
  return {
    LazyNormal = { fg = p.fg, bg = c.transparent and p.none or p.bg1 },
    LazyButton = { fg = p.fg, bg = p.bg2 },
    LazyButtonActive = { fg = p.bg1, bg = p.lime, bold = true },
    LazyH1 = { fg = p.bg1, bg = p.lime, bold = true },
    LazyH2 = { fg = p.lime, bold = true },
    LazyComment = { fg = p.dim },
    LazyCommit = { fg = p.teal },
    LazyCommitIssue = { fg = p.sky },
    LazyCommitScope = { fg = p.lav },
    LazyCommitType = { fg = p.lime },
    LazyDimmed = { fg = p.dim },
    LazyDir = { fg = p.sky },
    LazyLocal = { fg = p.mint },
    LazyNoCond = { fg = p.rose },
    LazyProgressDone = { fg = p.lime },
    LazyProgressTodo = { fg = p.lnr },
    LazyProp = { fg = p.dim },
    LazyReasonCmd = { fg = p.mint },
    LazyReasonEvent = { fg = p.lav },
    LazyReasonFt = { fg = p.sky },
    LazyReasonImport = { fg = p.fg },
    LazyReasonKeys = { fg = p.lime },
    LazyReasonPlugin = { fg = p.lav },
    LazyReasonRequire = { fg = p.teal },
    LazyReasonRuntime = { fg = p.peach },
    LazyReasonSource = { fg = p.mint },
    LazyReasonStart = { fg = p.lime },
    LazySpecial = { fg = p.mint },
    LazyTaskError = { fg = p.rose },
    LazyTaskOutput = { fg = p.fg },
    LazyUrl = { fg = p.sky, underline = true },
    LazyValue = { fg = p.str },
  }
end
