-- markview.nvim (markdown rendering)
return function(p, c)
  return {
    MarkviewHeading1 = { fg = p.lime, bold = true },
    MarkviewHeading2 = { fg = p.mint, bold = true },
    MarkviewHeading3 = { fg = p.sky, bold = true },
    MarkviewHeading4 = { fg = p.lav, bold = true },
    MarkviewHeading5 = { fg = p.teal, bold = true },
    MarkviewHeading6 = { fg = p.fg2, bold = true },
    MarkviewHeading1Sign = { fg = p.lime },
    MarkviewHeading2Sign = { fg = p.mint },
    MarkviewHeading3Sign = { fg = p.sky },
    MarkviewHeading4Sign = { fg = p.lav },
    MarkviewHeading5Sign = { fg = p.teal },
    MarkviewHeading6Sign = { fg = p.fg2 },
    MarkviewCode = { bg = p.bg2 },
    MarkviewCodeInfo = { fg = p.dim, bg = p.bg2 },
    MarkviewCodeFg = { fg = p.fg },
    MarkviewInlineCode = { fg = p.str, bg = p.bg2 },
    MarkviewBlockQuoteDefault = { fg = p.fg2 },
    MarkviewBlockQuoteNote = { fg = p.steel },
    MarkviewBlockQuoteTip = { fg = p.mint },
    MarkviewBlockQuoteWarn = { fg = p.butter },
    MarkviewBlockQuoteError = { fg = p.rose },
    MarkviewBlockQuoteOk = { fg = p.mint },
    MarkviewBlockQuoteSpecial = { fg = p.lav },
    MarkviewListItemMinus = { fg = p.lime },
    MarkviewListItemPlus = { fg = p.mint },
    MarkviewListItemStar = { fg = p.lav },
    MarkviewCheckboxChecked = { fg = p.mint },
    MarkviewCheckboxUnchecked = { fg = p.dim },
    MarkviewCheckboxPending = { fg = p.butter },
    MarkviewCheckboxProgress = { fg = p.sky },
    MarkviewCheckboxCancelled = { fg = p.dim, strikethrough = true },
    MarkviewHyperlink = { fg = p.sky, underline = true },
    MarkviewImage = { fg = p.lav, underline = true },
    MarkviewEmail = { fg = p.sky, underline = true },
    MarkviewTableHeader = { fg = p.lime, bold = true },
    MarkviewTableBorder = { fg = p.border },
    MarkviewTableAlignLeft = { fg = p.border },
    MarkviewTableAlignRight = { fg = p.border },
    MarkviewTableAlignCenter = { fg = p.border },
    MarkviewHorizontalRule = { fg = p.border },
    MarkviewIcon0 = { fg = p.fg2 },
    MarkviewIcon1 = { fg = p.rose },
    MarkviewIcon2 = { fg = p.butter },
    MarkviewIcon3 = { fg = p.lime },
    MarkviewIcon4 = { fg = p.sky },
    MarkviewIcon5 = { fg = p.lav },
    MarkviewIcon6 = { fg = p.teal },
    MarkviewPalette0 = { fg = p.fg2, bg = p.bg2 },
    MarkviewPalette1 = { fg = p.rose, bg = p.bg2 },
    MarkviewPalette2 = { fg = p.butter, bg = p.bg2 },
    MarkviewPalette3 = { fg = p.lime, bg = p.bg2 },
    MarkviewPalette4 = { fg = p.sky, bg = p.bg2 },
    MarkviewPalette5 = { fg = p.lav, bg = p.bg2 },
    MarkviewPalette6 = { fg = p.teal, bg = p.bg2 },
    MarkviewPalette0Fg = { fg = p.fg2 },
    MarkviewPalette1Fg = { fg = p.rose },
    MarkviewPalette2Fg = { fg = p.butter },
    MarkviewPalette3Fg = { fg = p.lime },
    MarkviewPalette4Fg = { fg = p.sky },
    MarkviewPalette5Fg = { fg = p.lav },
    MarkviewPalette6Fg = { fg = p.teal },
  }
end
