return function(p, c)
  local bg = c.transparent and p.none or p.bg1
  return {
    NoiceCmdline = { fg = p.fg },
    NoiceCmdlinePopup = { fg = p.fg, bg = bg },
    NoiceCmdlinePopupBorder = { fg = p.border, bg = p.none },
    NoiceCmdlinePopupTitle = { fg = p.lime, bold = true },
    NoiceCmdlinePopupBorderSearch = { fg = p.mint, bg = p.none },
    NoiceCmdlineIcon = { fg = p.lime },
    NoiceCmdlineIconSearch = { fg = p.mint },
    NoiceCmdlineIconLua = { fg = p.sky },
    NoiceCmdlineIconHelp = { fg = p.lav },
    NoiceCmdlinePrompt = { fg = p.lime },
    NoiceConfirm = { fg = p.fg, bg = bg },
    NoiceConfirmBorder = { fg = p.border, bg = p.none },
    NoiceMini = { fg = p.fg, bg = p.none },
    NoicePopup = { fg = p.fg, bg = bg },
    NoicePopupBorder = { fg = p.border, bg = p.none },
    NoicePopupmenu = { fg = p.fg, bg = bg },
    NoicePopupmenuBorder = { fg = p.border, bg = p.none },
    NoicePopupmenuMatch = { fg = p.cursor, bold = true },
    NoicePopupmenuSelected = { fg = p.bg1, bg = p.mintVivid, bold = true },
    NoiceScrollbar = { bg = p.bg2 },
    NoiceScrollbarThumb = { bg = p.bg4 },
    NoiceSplit = { fg = p.fg, bg = p.none },
    NoiceSplitBorder = { fg = p.border },
    NoiceVirtualText = { fg = p.dim },
    NoiceFormatProgressDone = { fg = p.bg1, bg = p.lime },
    NoiceFormatProgressTodo = { fg = p.fg2, bg = p.bg3 },
    NoiceFormatTitle = { fg = p.lime, bold = true },
    NoiceFormatEvent = { fg = p.dim },
    NoiceFormatKind = { fg = p.dim },
    NoiceFormatDate = { fg = p.dim },
    NoiceFormatConfirm = { fg = p.bg1, bg = p.mint },
    NoiceFormatConfirmDefault = { fg = p.bg1, bg = p.lime },
    NoiceFormatLevelError = { fg = p.rose },
    NoiceFormatLevelWarn = { fg = p.butter },
    NoiceFormatLevelInfo = { fg = p.steel },
    NoiceFormatLevelDebug = { fg = p.dim },
    NoiceFormatLevelTrace = { fg = p.lav },
    NoiceFormatLevelOff = { fg = p.lnr },
    NoiceLspProgressTitle = { fg = p.fg },
    NoiceLspProgressClient = { fg = p.lime },
    NoiceLspProgressSpinner = { fg = p.mint },
    NoiceCompletionItemKindDefault = { fg = p.lime },
    NoiceCompletionItemMenu = { fg = p.dim },
    NoiceCompletionItemWord = { fg = p.fg },
  }
end
