-- snacks.nvim: picker, notifier, input, indent, dashboard, statuscolumn, words
return function(p, c)
  local bg = c.transparent and p.none or p.bg1
  return {
    SnacksNormal = { fg = p.fg, bg = bg },
    SnacksNormalNC = { fg = p.fg, bg = bg },
    SnacksWinBar = { fg = p.lime, bold = true },
    SnacksWinBarNC = { fg = p.dim },
    SnacksBackdrop = { bg = p.bg0 },

    SnacksPicker = { fg = p.fg, bg = bg },
    SnacksPickerBorder = { fg = p.border, bg = p.none },
    SnacksPickerTitle = { fg = p.lime, bold = true },
    SnacksPickerFooter = { fg = p.dim },
    SnacksPickerPrompt = { fg = p.lime },
    SnacksPickerInput = { fg = p.fg, bg = bg },
    SnacksPickerInputBorder = { fg = p.border, bg = p.none },
    SnacksPickerInputTitle = { fg = p.lime, bold = true },
    SnacksPickerInputSearch = { fg = p.op },
    SnacksPickerList = { fg = p.fg, bg = bg },
    SnacksPickerListCursorLine = { bg = p.bg3 },
    SnacksPickerPreviewCursorLine = { bg = p.bg2 },
    SnacksPickerMatch = { fg = p.op, bold = true },
    SnacksPickerSelected = { fg = p.lime, bold = true },
    SnacksPickerToggle = { fg = p.bg1, bg = p.mint },
    SnacksPickerDir = { fg = p.dim },
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerPathHidden = { fg = p.dim },
    SnacksPickerPathIgnored = { fg = p.lnr },
    SnacksPickerRow = { fg = p.lnr },
    SnacksPickerCol = { fg = p.lnr },
    SnacksPickerDelim = { fg = p.lnr },
    SnacksPickerGitStatusAdded = { fg = p.mintPale },
    SnacksPickerGitStatusModified = { fg = p.butter },
    SnacksPickerGitStatusDeleted = { fg = p.pink },
    SnacksPickerGitStatusUntracked = { fg = p.dim },
    SnacksPickerGitBranch = { fg = p.lav },
    SnacksPickerGitCommit = { fg = p.teal },
    SnacksPickerGitDate = { fg = p.dim },
    SnacksPickerDiagnosticError = { fg = p.rose },
    SnacksPickerDiagnosticWarn = { fg = p.lspWarn },
    SnacksPickerDiagnosticInfo = { fg = p.steel },
    SnacksPickerDiagnosticHint = { fg = p.limeSoft },
    SnacksPickerCode = { fg = p.teal },
    SnacksPickerBold = { bold = true },
    SnacksPickerItalic = { italic = true },
    SnacksPickerSpecial = { fg = p.mint },
    SnacksPickerKeymapLhs = { fg = p.lime },
    SnacksPickerKeymapRhs = { fg = p.fg2 },
    SnacksPickerRegister = { fg = p.lav },
    SnacksPickerManDesc = { fg = p.fg2 },
    SnacksPickerBufFlags = { fg = p.dim },
    SnacksPickerBufNr = { fg = p.lnr },
    SnacksPickerIdx = { fg = p.lnr },
    SnacksPickerSearch = { fg = p.op, bold = true },
    SnacksPickerUnselected = { fg = p.dim },
    SnacksPickerAuCmd = { fg = p.teal },
    SnacksPickerAuEvent = { fg = p.lime },
    SnacksPickerAuGroup = { fg = p.lav },
    SnacksPickerAuPattern = { fg = p.str },
    SnacksPickerIconSource = { fg = p.mint },
    SnacksPickerIconCategory = { fg = p.sky },
    SnacksPickerIconName = { fg = p.fg },
    SnacksPickerIconFile = { fg = p.fg },

    SnacksInput = { fg = p.fg, bg = bg },
    SnacksInputBorder = { fg = p.border, bg = p.none },
    SnacksInputTitle = { fg = p.lime, bold = true },
    SnacksInputIcon = { fg = p.lime },
    SnacksInputPrompt = { fg = p.lime },

    SnacksNotifierInfo = { fg = p.fg, bg = bg },
    SnacksNotifierWarn = { fg = p.fg, bg = bg },
    SnacksNotifierError = { fg = p.fg, bg = bg },
    SnacksNotifierDebug = { fg = p.fg, bg = bg },
    SnacksNotifierTrace = { fg = p.fg, bg = bg },
    SnacksNotifierBorderInfo = { fg = p.mint, bg = p.none },
    SnacksNotifierBorderWarn = { fg = p.butter, bg = p.none },
    SnacksNotifierBorderError = { fg = p.rose, bg = p.none },
    SnacksNotifierBorderDebug = { fg = p.dim, bg = p.none },
    SnacksNotifierBorderTrace = { fg = p.lav, bg = p.none },
    SnacksNotifierIconInfo = { fg = p.mint },
    SnacksNotifierIconWarn = { fg = p.butter },
    SnacksNotifierIconError = { fg = p.rose },
    SnacksNotifierIconDebug = { fg = p.dim },
    SnacksNotifierIconTrace = { fg = p.lav },
    SnacksNotifierTitleInfo = { fg = p.lime, bold = true },
    SnacksNotifierTitleWarn = { fg = p.butter, bold = true },
    SnacksNotifierTitleError = { fg = p.rose, bold = true },
    SnacksNotifierTitleDebug = { fg = p.dim, bold = true },
    SnacksNotifierTitleTrace = { fg = p.lav, bold = true },
    SnacksNotifierFooterInfo = { fg = p.dim },
    SnacksNotifierFooterWarn = { fg = p.dim },
    SnacksNotifierFooterError = { fg = p.dim },
    SnacksNotifierFooterDebug = { fg = p.dim },
    SnacksNotifierFooterTrace = { fg = p.dim },
    SnacksNotifierHistory = { fg = p.fg, bg = bg },
    SnacksNotifierHistoryTitle = { fg = p.lime, bold = true },
    SnacksNotifierHistoryDateTime = { fg = p.dim },

    SnacksIndent = { fg = p.lnr },
    SnacksIndentScope = { fg = p.dim },
    SnacksIndentChunk = { fg = p.dim },
    SnacksIndentBlank = { fg = p.none },
    SnacksIndent1 = { fg = p.lnr },
    SnacksIndent2 = { fg = p.lnr },
    SnacksIndent3 = { fg = p.lnr },
    SnacksIndent4 = { fg = p.lnr },
    SnacksIndent5 = { fg = p.lnr },
    SnacksIndent6 = { fg = p.lnr },
    SnacksIndent7 = { fg = p.lnr },
    SnacksIndent8 = { fg = p.lnr },

    SnacksDashboardNormal = { fg = p.fg, bg = p.none },
    SnacksDashboardHeader = { fg = p.lime },
    SnacksDashboardTitle = { fg = p.lime, bold = true },
    SnacksDashboardIcon = { fg = p.lime },
    SnacksDashboardKey = { fg = p.mint },
    SnacksDashboardDesc = { fg = p.fg },
    SnacksDashboardFile = { fg = p.fg },
    SnacksDashboardDir = { fg = p.dim },
    SnacksDashboardFooter = { fg = p.dim },
    SnacksDashboardSpecial = { fg = p.lav },
    SnacksDashboardTerminal = { fg = p.fg2 },

    SnacksStatusColumnMark = { fg = p.lime },
    SnacksStatusColumnFold = { fg = p.lnr },
    SnacksScratchKey = { fg = p.lime },
    SnacksScratchDesc = { fg = p.fg2 },
    SnacksZenIcon = { fg = p.lime },
    SnacksDim = { fg = p.dim },
    SnacksProfilerBadgeInfo = { fg = p.bg1, bg = p.steel },
    SnacksProfilerBadgeTrace = { fg = p.bg1, bg = p.lav },
    SnacksTerminal = { fg = p.fg, bg = p.none },
    SnacksImageMath = { fg = p.teal },
    SnacksImageLoading = { fg = p.dim, italic = true },
  }
end
