-- Editor chrome: grounds, cursor line, search, menus, splits, messages, diffs.
return function(p, c)
  local t = c.transparent
  local bg = t and p.none or p.bg1
  return {
    Normal = { fg = p.fg, bg = bg },
    NormalNC = { fg = p.fg, bg = bg },
    NormalFloat = { fg = p.fg, bg = bg },
    FloatBorder = { fg = p.border, bg = p.none },
    FloatTitle = { fg = p.lime, bg = p.none, bold = true },
    FloatFooter = { fg = p.dim, bg = p.none },

    Cursor = { fg = p.bg1, bg = p.cursor },
    lCursor = { fg = p.bg1, bg = p.cursor },
    CursorIM = { fg = p.bg1, bg = p.cursor },
    TermCursor = { fg = p.bg1, bg = p.cursor },
    TermCursorNC = { fg = p.bg1, bg = p.dim },
    CursorLine = { bg = p.bg2 },
    CursorColumn = { bg = p.bg2 },
    ColorColumn = { bg = p.bg2 },
    CursorLineNr = { fg = p.lime, bold = true },
    LineNr = { fg = p.lnr },
    LineNrAbove = { fg = p.lnr },
    LineNrBelow = { fg = p.lnr },
    SignColumn = { fg = p.lnr, bg = p.none },
    FoldColumn = { fg = p.lnr, bg = p.none },
    Folded = { fg = p.dim, bg = p.bg2 },

    Visual = { bg = p.bg3 },
    VisualNOS = { bg = p.bg3 },
    Search = { fg = p.search, bg = p.none, bold = true },
    IncSearch = { fg = p.search, bg = p.none, bold = true },
    CurSearch = { fg = p.bg1, bg = p.search, bold = true },
    Substitute = { fg = p.bg1, bg = p.butter },
    MatchParen = { fg = p.mintVivid, bold = true, underline = true },

    Pmenu = { fg = p.fg, bg = bg },
    PmenuSel = { fg = p.bg1, bg = p.mintVivid, bold = true },
    PmenuKind = { fg = p.lime, bg = bg },
    PmenuKindSel = { fg = p.bg1, bg = p.mintVivid },
    PmenuExtra = { fg = p.dim, bg = bg },
    PmenuExtraSel = { fg = p.bg1, bg = p.mintVivid },
    PmenuSbar = { bg = p.bg2 },
    PmenuThumb = { bg = p.bg4 },
    PmenuMatch = { fg = p.cursor, bold = true },
    PmenuMatchSel = { fg = p.bg1, bg = p.mintVivid, bold = true },
    WildMenu = { fg = p.bg1, bg = p.mintVivid, bold = true },

    EndOfBuffer = { fg = p.bg4, bg = bg },
    NonText = { fg = p.lnr },
    Whitespace = { fg = p.lnr },
    SpecialKey = { fg = p.lnr },
    Conceal = { fg = p.dim },

    WinSeparator = { fg = p.border, bg = p.none },
    VertSplit = { fg = p.border, bg = p.none },
    StatusLine = { fg = p.fg, bg = p.bg1 },
    StatusLineNC = { fg = c.dim_inactive and p.dim or p.fg2, bg = p.bg1 },
    StatusLineTerm = { fg = p.fg, bg = p.bg1 },
    StatusLineTermNC = { fg = p.dim, bg = p.bg1 },
    WinBar = { fg = p.fg2, bg = p.none },
    WinBarNC = { fg = p.dim, bg = p.none },
    TabLine = { fg = p.dim, bg = p.bg1 },
    TabLineSel = { fg = p.bg1, bg = p.lime, bold = true },
    TabLineFill = { bg = p.bg1 },

    Title = { fg = p.lime, bold = true },
    Directory = { fg = p.sky },
    ModeMsg = { fg = p.lime, bold = true },
    MsgArea = { fg = p.fg },
    MsgSeparator = { fg = p.border, bg = p.bg1 },
    MoreMsg = { fg = p.mint },
    Question = { fg = p.mint },
    ErrorMsg = { fg = p.rose },
    WarningMsg = { fg = p.butter },
    NvimInternalError = { fg = p.rose },
    QuickFixLine = { bg = p.bg2, bold = true },
    qfLineNr = { fg = p.lnr },
    qfFileName = { fg = p.sky },

    DiffAdd = { bg = p.diffAdded },
    DiffChange = { bg = p.bg2 },
    DiffDelete = { fg = p.pink, bg = p.diffRemoved },
    DiffText = { bg = p.diffAddedWord, bold = true },
    Added = { fg = p.mintPale },
    Changed = { fg = p.butter },
    Removed = { fg = p.pink },
    diffAdded = { fg = p.mintPale },
    diffRemoved = { fg = p.pink },
    diffChanged = { fg = p.butter },
    diffOldFile = { fg = p.pink },
    diffNewFile = { fg = p.mintPale },
    diffFile = { fg = p.sky },
    diffLine = { fg = p.dim },
    diffIndexLine = { fg = p.lav },

    SpellBad = { sp = p.rose, undercurl = true },
    SpellCap = { sp = p.butter, undercurl = true },
    SpellLocal = { sp = p.steel, undercurl = true },
    SpellRare = { sp = p.lav, undercurl = true },

    healthError = { fg = p.rose },
    healthSuccess = { fg = p.mint },
    healthWarning = { fg = p.butter },
  }
end
