-- Diagnostics and LSP semantic tokens. Virtual text keeps a transparent
-- background on purpose; the sign column carries the colour.
return function(p, c)
  local fn = c.styles.functions or {}
  return {
    DiagnosticError = { fg = p.rose },
    DiagnosticWarn = { fg = p.lspWarn },
    DiagnosticInfo = { fg = p.steel },
    DiagnosticHint = { fg = p.limeSoft },
    DiagnosticOk = { fg = p.mint },
    DiagnosticVirtualTextError = { fg = p.rose, bg = p.none },
    DiagnosticVirtualTextWarn = { fg = p.lspWarn, bg = p.none },
    DiagnosticVirtualTextInfo = { fg = p.steel, bg = p.none },
    DiagnosticVirtualTextHint = { fg = p.limeSoft, bg = p.none },
    DiagnosticVirtualTextOk = { fg = p.mint, bg = p.none },
    DiagnosticUnderlineError = { sp = p.rose, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.lspWarn, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.steel, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.limeSoft, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.mint, undercurl = true },
    DiagnosticSignError = { fg = p.rose, bg = p.none },
    DiagnosticSignWarn = { fg = p.lspWarn, bg = p.none },
    DiagnosticSignInfo = { fg = p.steel, bg = p.none },
    DiagnosticSignHint = { fg = p.limeSoft, bg = p.none },
    DiagnosticFloatingError = { fg = p.rose },
    DiagnosticFloatingWarn = { fg = p.lspWarn },
    DiagnosticFloatingInfo = { fg = p.steel },
    DiagnosticFloatingHint = { fg = p.limeSoft },
    DiagnosticDeprecated = { sp = p.dim, strikethrough = true },
    DiagnosticUnnecessary = { fg = p.dim, italic = true },

    LspReferenceText = { bg = p.bg3 },
    LspReferenceRead = { bg = p.bg3 },
    LspReferenceWrite = { bg = p.bg3, underline = true },
    LspReferenceTarget = { bg = p.bg3 },
    LspInlayHint = { fg = p.dim, bg = p.none, italic = true },
    LspCodeLens = { fg = p.dim },
    LspCodeLensSeparator = { fg = p.lnr },
    LspSignatureActiveParameter = { fg = p.lime, bold = true },
    LspInfoBorder = { fg = p.border },

    ["@lsp.type.class"] = { fg = p.type },
    ["@lsp.type.comment"] = { fg = p.dim },
    ["@lsp.type.decorator"] = { fg = p.lime },
    ["@lsp.type.enum"] = { fg = p.type },
    ["@lsp.type.enumMember"] = { fg = p.teal },
    ["@lsp.type.function"] = { fg = p.func, bold = fn.bold },
    ["@lsp.type.interface"] = { fg = p.type },
    ["@lsp.type.keyword"] = { fg = p.lime },
    ["@lsp.type.macro"] = { fg = p.limeDeep },
    ["@lsp.type.method"] = { fg = p.func, bold = fn.bold },
    ["@lsp.type.namespace"] = { fg = p.fg2 },
    ["@lsp.type.number"] = { fg = p.teal },
    ["@lsp.type.operator"] = { fg = p.op },
    ["@lsp.type.parameter"] = { fg = p.ident },
    ["@lsp.type.property"] = { fg = p.ident },
    ["@lsp.type.string"] = { fg = p.str },
    ["@lsp.type.struct"] = { fg = p.type },
    ["@lsp.type.type"] = { fg = p.type },
    ["@lsp.type.typeParameter"] = { fg = p.type, italic = true },
    ["@lsp.type.variable"] = { fg = p.ident },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = p.func, bold = fn.bold },
    ["@lsp.typemod.variable.readonly"] = { fg = p.teal },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = p.sky, italic = true },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
  }
end
