-- voidrunner: generated by lanteignel93/dotfiles theme/render.py; do not edit here.
-- Drop the cached palette and highlight modules, so a re-render (dye render /
-- publish) shows on the next :colorscheme without restarting nvim. The main
-- module stays: it holds the setup() options (transparent, styles).
for mod in pairs(package.loaded) do
  if mod:find("^voidrunner%.") then package.loaded[mod] = nil end
end
require("voidrunner").load()
