-- voidrunner: generated by lanteignel93/dotfiles theme/render.py; do not edit here.
-- Drop cached modules first, so a re-render (dye render / publish) shows on the
-- next :colorscheme in a running nvim instead of needing a restart.
for mod in pairs(package.loaded) do
  if mod == "voidrunner" or mod:find("^voidrunner%.") then package.loaded[mod] = nil end
end
require("voidrunner").load()
