-- voidrunner — generated by ~/dotfiles/theme/render.py; do not edit
-- Overlay for awesome's theme.lua: it does
--   local ok, t = pcall(dofile, os.getenv("HOME") .. "/.config/theme/current/awesome.lua")
--   if ok and type(t) == "table" then for k, v in pairs(t) do theme[k] = v end end
-- right before `return theme`, so every key here wins over the file's own.
return {
  bg_normal     = "#1c1c1c",
  bg_focus      = "#303030",
  bg_urgent     = "#dea6a0",
  bg_minimize   = "#3c3c3c",
  bg_systray    = "#1c1c1c",

  fg_normal     = "#c0c0c0",
  fg_focus      = "#f1f1f1",
  fg_urgent     = "#1c1c1c",
  fg_minimize   = "#585858",

  border_normal = "#e5ccff",
  border_focus  = "#5eeeaf",
  border_marked = "#dea6a0",

  taglist_bg_focus    = "#bdfe58",
  taglist_fg_focus    = "#1c1c1c",
  taglist_bg_urgent   = "#dea6a0",
  taglist_fg_urgent   = "#1c1c1c",
  taglist_bg_occupied = "#262626",
  taglist_fg_occupied = "#c0c0c0",
  taglist_fg_empty    = "#585858",

  tasklist_bg_focus   = "#303030",
  tasklist_fg_focus   = "#f1f1f1",
  tasklist_bg_urgent  = "#dea6a0",
  tasklist_fg_urgent  = "#1c1c1c",

  titlebar_bg_normal  = "#1c1c1c",
  titlebar_bg_focus   = "#262626",
  titlebar_fg_normal  = "#585858",
  titlebar_fg_focus   = "#c0c0c0",

  tooltip_bg          = "#1c1c1c",
  tooltip_fg          = "#c0c0c0",
  tooltip_border_color = "#585858",

  notification_bg     = "#1c1c1c",
  notification_fg     = "#c0c0c0",
  notification_border_color = "#585858",

  menu_bg_normal      = "#1c1c1c",
  menu_bg_focus       = "#303030",
  menu_fg_normal      = "#c0c0c0",
  menu_fg_focus       = "#f1f1f1",
  menu_border_color   = "#585858",

  prompt_bg           = "#1c1c1c",
  prompt_fg           = "#bdfe58",
  prompt_fg_cursor    = "#1c1c1c",
  prompt_bg_cursor    = "#bdfe58",
}
